services:
  - type: web
    name: agrointel-backend
    env: python
    buildCommand: pip install --upgrade pip && pip install --only-binary=scikit-learn,numpy,scipy,cython -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GRPC_ENABLE_FORK_SUPPORT
        value: 0
      - key: GRPC_POLL_STRATEGY
        value: epoll1
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://agrointel-5089b.web.app,https://agrointel-5089b.firebaseapp.com,http://localhost:3000
      - key: PORT
        value: 8000
    buildFilter:
      paths:
      - requirements.txt
      - app.py
    plan: free